### ISSUE TITLE
Testing home page renders after adding sessions

### ISSUE THREAD

**Issue by bytrangle** [EthanRBrown/web-development-with-node-and-express-2e#59]
In chapter 10, we introduced sessions:
```js
// meadowlark.js

app.get('/', (req, res) => {
  const cart = req.session.cart || { items: [] }
  const context = { products, cart }
  res.render('home', context)
})
```
In your repo, at this point, you have removed the test for rendering home page at `__tests__/handlers.test.js`.

```js
test('home page renders', () => {
  const req = {}
  const res = { render: jest.fn() }
  handlers.home(req, res)
  expect(res.render.mock.calls.length).toBe(1)
  expect(res.render.mock.calls[0][0]).toBe('home')
})
```

But assuming that we still have the test file  and run it, the test would fail with the following error:
> TypeError: Cannot read property 'cart' of undefined
 
because in the test, we only pass the `req` parameter  an empty object `{}`. Hence, in the home page handler, `req.session` is undefined, and calling `req.session.cart` would throw an error.

I rewrote the route handler to accommodate the test:
```js
exports.home = (req, res) => {
  const cart = req.session && req.session.cart ? req.session.cart : { items: [] };
  const context = { products, cart };
  res.render('home', context)
}
```
But is it the right thing to do?

**Comment by EthanRBrown** [comment]
Hi, Trang, thank you for the question!  I’m at the airport, leaving for my
first post-pandemic trip, and I *don’t* have my laptop with me (hooray)!
I’ll be back on the 6th & will take a look at your question then.  Sorry
for the delay, and thank you for your patience!

**Comment by EthanRBrown** [comment]
Hi, @bytrangle , I'm so sorry I let this drop...better late than never?

There are two ways to handle this, of course: make the test more robust by adding a `session` object, or doing what you did.  I think in this instance, it's probably better to update the tests since it would be onerous to check for the existence of `session` in _every_ handler...after all, the `express-session` middleware ensures the existence of `session`, so you probably want it to blow if up if it doesn't exist...that indicates something deeper is wrong, and you don't want to sweep it under the rug.  So I would modify the test instead:

```js
test('home page renders', () => {
  const req = { session: {} }  // <-- this is the change
  const res = { render: jest.fn() }
  handlers.home(req, res)
  expect(res.render.mock.calls.length).toBe(1)
  expect(res.render.mock.calls[0][0]).toBe('home')
})
```


```js
exports.home = (req, res) => {
  const cart = req?.session?.cart || { items: [] }
  const context = { products, cart }
  res.render('home', context)
}
```

The next time I refresh this book, I'll take a closer look at providing more comprehensive test examples.  Thanks again for your excellent question, and again I apologize for the delay!  My 2023 resolution is to stay on top of book questions.
